name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies (Linux-compatible)
        run: |
          cd lambda/process_audio
          pip install -r requirements.txt -t ./package

      - name: Build ZIP for Lambda
        run: |
          cd lambda/process_audio/package
          zip -r9 ../function.zip .
          cd ..
          zip -g function.zip lambda_function.py

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.2.16
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ProcessIdeaAudioLambda-dev
          zip_file: lambda/process_audio/function.zip
