name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # -----------------------------
      # Detectar qu√© Lambdas cambiaron
      # -----------------------------
      - name: Detect changed lambdas
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            process_audio:
              - 'lambda/process_audio/**'
            upload_url:
              - 'lambda/get_upload_url/**'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # =============================
      # ProcessAudioLambda
      # =============================
      - name: Install dependencies (process_audio)
        if: steps.changes.outputs.process_audio == 'true'
        run: |
          cd lambda/process_audio
          pip install -r requirements.txt -t ./package

      - name: Build ZIP (process_audio)
        if: steps.changes.outputs.process_audio == 'true'
        run: |
          cd lambda/process_audio/package
          zip -r9 ../function.zip .
          cd ..
          zip -g function.zip lambda_function.py
          zip -g function.zip prompt.txt

      # =============================
      # GetUploadURL Lambda
      # =============================
      - name: Build ZIP (get_upload_url)
        if: steps.changes.outputs.upload_url == 'true'
        run: |
          cd lambda/get_upload_url
          zip -r function.zip lambda_function.py

      # -----------------------------
      # AWS Creds
      # -----------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # -----------------------------
      # Deploy process_audio
      # -----------------------------
      - name: Deploy process_audio lambda
        if: steps.changes.outputs.process_audio == 'true'
        run: |
          aws lambda update-function-code \
            --function-name ProcessIdeaAudioLambda-dev \
            --zip-file fileb://lambda/process_audio/function.zip

      # -----------------------------
      # Deploy get_upload_url
      # -----------------------------
      - name: Deploy get_upload_url lambda
        if: steps.changes.outputs.upload_url == 'true'
        run: |
          aws lambda update-function-code \
            --function-name GetUploadUrlLambda-dev \
            --zip-file fileb://lambda/get_upload_url/function.zip
